setup: cleanup namespace
Add an underscore (_) to all object names in an effort to try to ensure this
script doesn't clobber something already defined in the user's shell.

Add a cleanup trap to unset all objects which were introduced by the script on
all return paths including error situations.

Signed-off-by: Trevor Woerner <twoerner@gmail.com>

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -17,12 +17,59 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
+# cleanup on return
+__orc_cleanup() {
+	unset __orc_OEROOT __orc_TEMPLATECONF __orc_CMDLINEOPTS
+	unset __orc_tmpMACHINES __orc_MAC __orc_MACHLAYR __orc_MACHINES
+	unset __orc_tmpSDKMACHINES __orc_SDKMACHINES
+	unset __orc_tmpDISTROS __orc_DIS __orc_DISTLYR __orc_DISTROS
+	unset __orc_NEWPATHS __orc_IMAGETARGETS
+	if [ $__orc_MACHINEdefined -ne 1 ]; then
+		unset MACHINE
+	fi
+	if [ $__orc_SDKMACHINEdefined -ne 1 ]; then
+		unset SDKMACHINE
+	fi
+	if [ $__orc_DISTROdefined -ne 1 ]; then
+		unset DISTRO
+	fi
+	if [ $__orc_DLDIRdefined -ne 1 ]; then
+		unset DL_DIR
+	fi
+	unset __orc_MACHINEdefined __orc_SDKMACHINEdefined __orc_DISTROdefined __orc_DLDIRdefined
+	if [ -n "$BUILDDIR" ]; then
+		export BUILDDIR
+	fi
+
+	unset __orc_choose __orc_dldir __orc_machinesNlayers __orc_sdkmachines __orc_distrosNlayers __orc_imagesNlayers
+	unset __orc_cleanup
+}
+trap __orc_cleanup RETURN
+
+# check for some variables to see if they're already defined
+__orc_MACHINEdefined=0
+__orc_SDKMACHINEdefined=0
+__orc_DISTROdefined=0
+__orc_DLDIRdefined=0
+if [ -n "$MACHINE" ]; then
+	__orc_MACHINEdefined=1
+fi
+if [ -n "$SDKMACHINE" ]; then
+	__orc_SDKMACHINEdefined=1
+fi
+if [ -n "$DISTRO" ]; then
+	__orc_DISTROdefined=1
+fi
+if [ -n "$DL_DIR" ]; then
+	__orc_DLDIRdefined=1
+fi
+
 # $1 - an array of choices
 # $2 - an array of the layers corresponding 1:1 with the choices in $1 (optional)
 # $3 - title
 # $4 - selection help
 # return - what the user chose, or ""
-choose() {
+__orc_choose() {
 	local _MENULIST=""
 	local _i
 	local -a _CHOICES=("${!1}")
@@ -80,30 +127,30 @@ choose() {
 	echo $_CHOICE
 }
 
-dldir() {
-	local _dldir=""
+__orc_dldir() {
+	local _tmpdldir=""
 	local _helpstring="Please indicate the location of your DL_DIR (downloads directory): "
 
 	help read > /dev/null 2>&1
 	if [ $? -eq 0 ]; then
-		read -e -p "$_helpstring" _dldir
+		read -e -p "$_helpstring" _tmpdldir
 	else
 		which dialog > /dev/null 2>&1
 		if [ $? -eq 0 ]; then
-			_dldir=$(dialog --inputbox "$_helpstring" 0 0 3>&1 1>&2 2>&3)
+			_tmpdldir=$(dialog --inputbox "$_helpstring" 0 0 3>&1 1>&2 2>&3)
 		else
 			which whiptail > /dev/null 2>&1
 			if [ $? -eq 0 ]; then
-				_dldir=$(whiptail --inputbox "$_helpstring" 0 0 3>&1 1>&2 2>&3)
+				_tmpdldir=$(whiptail --inputbox "$_helpstring" 0 0 3>&1 1>&2 2>&3)
 			fi
 		fi
 	fi
 
-	echo $_dldir
+	echo $_tmpdldir
 }
 
 # return in $1 all known MACHINEs(layer)
-machinesNlayers() {
+__orc_machinesNlayers() {
 	local _outvar=$1
 	local _tmp
 
@@ -112,7 +159,7 @@ machinesNlayers() {
 }
 
 # return in $1 all SDKMACHINEs
-sdkmachines() {
+__orc_sdkmachines() {
 	local _outvar=$1
 	local _tmp
 
@@ -121,7 +168,7 @@ sdkmachines() {
 }
 
 # return in $1 all DISTROs(layers)
-distrosNlayers() {
+__orc_distrosNlayers() {
 	local _outvar=$1
 	local _tmp
 
@@ -131,7 +178,7 @@ distrosNlayers() {
 }
 
 # return in $1 all IMAGEs(layers)
-imagesNlayers() {
+__orc_imagesNlayers() {
 	local _outvar=$1
 	local _tmp
 
@@ -139,46 +186,46 @@ imagesNlayers() {
 	eval $_outvar="'$_tmp'"
 }
 
-OEROOT=$PWD
+__orc_OEROOT=$PWD
 
 if [ "$0" = "$BASH_SOURCE" ]; then
 	# check we're in the right location
-	if [ ! -d $OEROOT/layers ]; then
+	if [ ! -d $__orc_OEROOT/layers ]; then
 		echo "It doesn't look like I'm being run in the correct location."
 		echo "I can't find where the layers are stored."
-		echo "\$OEROOT/layers: $OEROOT/layers"
+		echo "\$__orc_OEROOT/layers: $__orc_OEROOT/layers"
 		exit 1
 	fi
 
 	if [ $# -eq 0 ]; then
-		CMDLINEOPTS="-m -s -d -i --"
+		__orc_CMDLINEOPTS="-m -s -d -i --"
 	else
-		CMDLINEOPTS=$(getopt -o msdic --long machines,sdkmachines,distros,images,config -- "$@")
+		__orc_CMDLINEOPTS=$(getopt -o msdic --long machines,sdkmachines,distros,images,config -- "$@")
 		if [ $? != 0 ]; then
 			echo "ERROR: bad cmdline"
 			exit 1
 		fi
 	fi
-	eval set -- "$CMDLINEOPTS"
+	eval set -- "$__orc_CMDLINEOPTS"
 	while true; do
 		case "$1" in
 			-m|--machines)
-				machinesNlayers MACHINES
+				__orc_machinesNlayers __orc_MACHINES
 				echo -e "\nAvailable Machines:"
-				echo $MACHINES | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
+				echo $__orc_MACHINES | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
 				;;
 			-s|--sdkmachines)
-				sdkmachines SDKMACHINES
+				__orc_sdkmachines __orc_SDKMACHINES
 				echo -e "\nAvailable SDK Machines:"
-				echo $SDKMACHINES | tr ' ' '\n' | sed -e 's/^/\t/'
+				echo $__orc_SDKMACHINES | tr ' ' '\n' | sed -e 's/^/\t/'
 				;;
 			-d|--distros)
-				distrosNlayers DISTROS
+				__orc_distrosNlayers __orc_DISTROS
 				echo -e "\nAvailable Distros:"
-				echo $DISTROS | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
+				echo $__orc_DISTROS | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
 				;;
 			-i|--images)
-				imagesNlayers IMAGES
+				__orc_imagesNlayers IMAGES
 				echo -e "\nAvailable Images:"
 				echo $IMAGES | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
 				;;
@@ -209,32 +256,27 @@ fi
 
 if [ "$(whoami)" = "root" ]; then
 	echo "ERROR: do not use this setup program as root!"
-	unset OEROOT BUILDDIR
 	return
 fi
 
 # check we're in the right location
-if [ ! -d $OEROOT/layers ]; then
+if [ ! -d $__orc_OEROOT/layers ]; then
 	echo "It doesn't look like I'm being run in the correct location."
 	echo "I can't find where the layers are stored."
-	unset OEROOT BUILDDIR
 	return
 fi
 
 ## choose a MACHINE
 if [ -z "$MACHINE" ]; then
-	declare -a MACHINES
-	declare -a MACHLAYR
-	machinesNlayers tmpMACHINES
-	for MAC in $tmpMACHINES; do
-		MACHINES+=($(echo $MAC | cut -d'(' -f1))
-		MACHLAYR+=($(echo $MAC | cut -d'(' -f2 | cut -d')' -f1))
+	declare -a __orc_MACHINES
+	declare -a __orc_MACHLAYR
+	__orc_machinesNlayers __orc_tmpMACHINES
+	for __orc_MAC in $__orc_tmpMACHINES; do
+		__orc_MACHINES+=($(echo $__orc_MAC | cut -d'(' -f1))
+		__orc_MACHLAYR+=($(echo $__orc_MAC | cut -d'(' -f2 | cut -d')' -f1))
 	done
-	unset tmpMACHINES
-	unset MAC
-	MACHINE=$(choose MACHINES[@] MACHLAYR[@] "Available machines" "Please choose a machine")
+	MACHINE=$(__orc_choose __orc_MACHINES[@] __orc_MACHLAYR[@] "Available machines" "Please choose a machine")
 	echo ""
-	unset MACHLAYR
 
 	# guard against Ctrl-D or cancel
 	if [ -z "$MACHINE" ]; then
@@ -244,20 +286,17 @@ if [ -z "$MACHINE" ]; then
 		echo "    MACHINE=<your-machine> . setup"
 		echo ""
 		echo "Possible <your-machine> choices are:"
-		echo ${MACHINES[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
-		unset OEROOT BUILDDIR MACHINE MACHINES
+		echo ${__orc_MACHINES[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
 		return
 	fi
-	unset MACHINES
 fi
 
 ## choose an SDKMACHINE
 if [ -z "$SDKMACHINE" ]; then
-	declare -a SDKMACHINES
-	sdkmachines tmpSDKMACHINES
-	SDKMACHINES=($tmpSDKMACHINES)
-	unset tmpSDKMACHINES
-	SDKMACHINE=$(choose SDKMACHINES[@] "" "Available SDKs" "Please choose an SDK machine")
+	declare -a __orc_SDKMACHINES
+	__orc_sdkmachines __orc_tmpSDKMACHINES
+	__orc_SDKMACHINES=($__orc_tmpSDKMACHINES)
+	SDKMACHINE=$(__orc_choose __orc_SDKMACHINES[@] "" "Available SDKs" "Please choose an SDK machine")
 	echo ""
 
 	if [ -z "$SDKMACHINE" ]; then
@@ -266,26 +305,21 @@ if [ -z "$SDKMACHINE" ]; then
 		echo "    SDKMACHINE=<your-sdk-machine> . setup"
 		echo ""
 		echo "Possible <your-sdk-machine> choices are:"
-		echo ${SDKMACHINES[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
-		unset OEROOT BUILDDIR MACHINE SDKMACHINE SDKMACHINES
+		echo ${__orc_SDKMACHINES[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
 		return
 	fi
-	unset SDKMACHINES
 fi
 
 ## choose a DISTRO
 if [ -z "$DISTRO" ]; then
-	declare -a DISTROS
-	distrosNlayers tmpDISTROS
-	for DIS in $tmpDISTROS; do
-		DISTROS+=($(echo $DIS | cut -d'(' -f1))
-		DISTLYR+=($(echo $DIS | cut -d'(' -f2 | cut -d')' -f1))
+	declare -a __orc_DISTROS
+	__orc_distrosNlayers __orc_tmpDISTROS
+	for __orc_DIS in $__orc_tmpDISTROS; do
+		__orc_DISTROS+=($(echo $__orc_DIS | cut -d'(' -f1))
+		__orc_DISTLYR+=($(echo $__orc_DIS | cut -d'(' -f2 | cut -d')' -f1))
 	done
-	unset tmpDISTROS
-	unset DIS
-	DISTRO=$(choose DISTROS[@] DISTLYR[@] "Available distros" "Please choose a distro")
+	DISTRO=$(__orc_choose __orc_DISTROS[@] __orc_DISTLYR[@] "Available distros" "Please choose a distro")
 	echo ""
-	unset DISTLYR
 
 	if [ -z "$DISTRO" ]; then
 		echo "To choose a distro interactively please install bash, dialog, or whiptail."
@@ -293,11 +327,9 @@ if [ -z "$DISTRO" ]; then
 		echo "    DISTRO=<your-distro> . setup"
 		echo ""
 		echo "Possible <your-distro> choices are:"
-		echo ${DISTROS[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
-		unset OEROOT BUILDDIR MACHINE SDKMACHINE DISTRO DISTROS
+		echo ${__orc_DISTROS[*]} | tr ' ' '\n' | sed -e 's/^/\t/'
 		return
 	fi
-	unset DISTROS
 fi
 if [ -z "$DISTRO" ]; then
 	DISTRO=poky
@@ -305,16 +337,15 @@ fi
 
 ## specify your DL_DIR
 if [ -z "$DL_DIR" ]; then
-	DL_DIR="$OEROOT/downloads"
-	DL_DIR=$(dldir)
+	DL_DIR="$__orc_OEROOT/downloads"
+	DL_DIR=$(__orc_dldir)
 fi
 
 # Clean up PATH, because if it includes tokens to current directories somehow,
 # wrong binaries can be used instead of the expected ones during task execution
 export PATH="$(echo ${PATH} | sed -e 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//')"
-NEWPATHS="$OEROOT/layers/openembedded-core/scripts:$OEROOT/bitbake/bin:"
-export PATH=$NEWPATHS$(echo $PATH | sed -e "s|:$NEWPATHS|:|g" -e "s|^$NEWPATHS||")
-unset NEWPATHS
+__orc_NEWPATHS="$__orc_OEROOT/layers/openembedded-core/scripts:$__orc_OEROOT/bitbake/bin:"
+export PATH=$__orc_NEWPATHS$(echo $PATH | sed -e "s|:$__orc_NEWPATHS|:|g" -e "s|^$__orc_NEWPATHS||")
 
 # Make sure Bitbake doesn't filter out the following variables from our environment.
 export BB_ENV_EXTRAWHITE="MACHINE DISTRO TCMODE TCLIBC HTTP_PROXY http_proxy \
@@ -323,13 +354,13 @@ all_proxy NO_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY \
 SDKMACHINE BB_NUMBER_THREADS BB_NO_NETWORK PARALLEL_MAKE GIT_PROXY_COMMAND \
 SOCKS5_PASSWD SOCKS5_USER SCREENDIR STAMPS_DIR"
 
-TEMPLATECONF=$OEROOT/.repo/manifests/conf
+__orc_TEMPLATECONF=$__orc_OEROOT/.repo/manifests/conf
 mkdir -p $BUILDDIR/conf
 if [ ! -r $BUILDDIR/conf/local.conf ]; then
-	cp $TEMPLATECONF/local.conf $BUILDDIR/conf/local.conf
+	cp $__orc_TEMPLATECONF/local.conf $BUILDDIR/conf/local.conf
 fi
 if [ ! -r $BUILDDIR/conf/bblayers.conf ]; then
-	sed -e "s|##OEROOT##|$OEROOT|g" $TEMPLATECONF/bblayers.conf > "$BUILDDIR/conf/bblayers.conf"
+	sed -e "s|##OEROOT##|$__orc_OEROOT|g" $__orc_TEMPLATECONF/bblayers.conf > "$BUILDDIR/conf/bblayers.conf"
 fi
 
 cat > $BUILDDIR/conf/auto.conf <<-EOF
@@ -337,18 +368,18 @@ cat > $BUILDDIR/conf/auto.conf <<-EOF
 	SDKMACHINE ?= "${SDKMACHINE}"
 	DISTRO ?= "${DISTRO}"
 	DL_DIR ?= "${DL_DIR}"
-	BBLAYERS_FETCH_DIR = "$OEROOT/layers"
+	BBLAYERS_FETCH_DIR = "$__orc_OEROOT/layers"
 EOF
 
 if [ ! -e $BUILDDIR/conf/site.conf ]; then
 	cat > $BUILDDIR/conf/site.conf <<-EOF
 		SCONF_VERSION = "1"
 		# Which files do we want to parse:
-		BBFILES ?= "${OEROOT}/layers/openembedded-core/meta/recipes-*/*/*.bb"
+		BBFILES ?= "${__orc_OEROOT}/layers/openembedded-core/meta/recipes-*/*/*.bb"
 	EOF
 fi
 
-imagesNlayers IMAGETARGETS
+__orc_imagesNlayers __orc_IMAGETARGETS
 cat <<EOF
 Your build environemnt has been configured with:
 
@@ -361,8 +392,7 @@ You can now run 'bitbake <target>'
 
 Some image targets are:
 EOF
-echo $IMAGETARGETS | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
-unset IMAGETARGETS
+echo $__orc_IMAGETARGETS | tr ' ' '\n' | sed -e 's/^/\t/' | sed -e 's/(/ (/'
 
 cd $BUILDDIR
 
@@ -376,5 +406,3 @@ if [ x"$DISTRO" != x"angstrom" ]; then
 		echo "from your conf/bblayers.conf manually."
 	fi
 fi
-
-unset OEROOT BUILDDIR MACHINE SDKMACHINE DISTRO DL_DIR
